// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcvbrwoxgiqdzuswzfcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjdmJyd294Z2lxZHp1c3d6ZmNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDgzMzUsImV4cCI6MjA2ODI4NDMzNX0.EX2hIKqRIlA40wj0itF4KGS7eZ4gnCrt2xtnuTKhEUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});